site_name: Rebellions Datasheet
nav:
    - Home: index.md
    - About: about.md
    - Datasheets:
        - RBLN-CA12:
            - English: en-rbln-ca12.md
            - Chinese: cn-rbln-ca12.md
theme: readthedocs
plugins:
    - search
    - pdf-export