site_name: Rebellions Datasheet
site_url: http://localhost/
nav:
    - Home: index.md
    - About: about.md
    - Datasheets:
        - RBLN-CA12:
            - English: en-rbln-ca12.md
            - Chinese: cn-rbln-ca12.md
theme: 
    name: readthedocs
extra_javascript:
  - assets/js/versioning.js
markdown_extensions:
    - md_in_html
plugins:
    - search
    - pdf-export:
        verbose: true
        media_type: pdf-export
        combined: false
extra_css:
  - extra.css
extra:
  version:
    alias: true
    provider: mike  