name: Deploy Site

on:
  workflow_dispatch:
  push:
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - 'requirements.txt'
    branches:
      - main
    tags-ignore:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install -r requirements.txt
      - name: Deploy Files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          mike deploy
          mike set-default dev --push